---
- name: Adicionar Máquina ao Zabbix (via API)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Obter o Token de Sessão do Zabbix
      uri:
        url: "{{ zabbix_api_url }}/api_jsonrpc.php"
        method: POST
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            user: "{{ zabbix_user }}"
            password: "{{ zabbix_password }}"
          id: 1
        headers:
          Content-Type: "application/json"
        return_content: yes
        validate_certs: no
      register: login_response

    - name: Exibir resposta do login
      debug:
        msg: "{{ login_response }}"

    - name: Adicionar Host no Zabbix
      uri:
        url: "{{ zabbix_api_url }}/api_jsonrpc.php"
        method: POST
        body:
          jsonrpc: "2.0"
          method: "host.create"
          params:
            host: "{{ vm_name }}"
            interfaces:
              - type: 1
                main: 1
                useip: 1
                ip: "{{ vm_ip }}"
                dns: ""
                port: "{{ zabbix_port }}"
            groups: "{{ zabbix_groups }}" 
            templates: "{{ zabbix_templates }}" 
          auth: "{{ login_response.json.result }}"
          id: 1
        headers:
          Content-Type: "application/json"
        return_content: yes
      register: create_host_response

    - name: Exibir resposta de criação de host
      debug:
        msg: "{{ create_host_response }}"
