---
- name: Adicionar Máquina ao Zabbix
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: "/etc/ansible/playbooks/venv/bin/python"

  vars_prompt:
    - name: vm_name
      prompt: "Qual o nome da máquina?"
      private: no

    - name: vm_ip
      prompt: "Qual o IP da máquina?"
      private: no

  tasks:
    - name: Obter o Token de Sessão do Zabbix
      community.zabbix.zabbix_api:
        url: "{{ zabbix_api_url }}"
        username: "{{ zabbix_user }}"
        password: "{{ zabbix_password }}"
        validate_certs: no
      register: zabbix_token

    - name: Adicionar Host no Zabbix
      community.zabbix.zabbix_host:
        url: "{{ zabbix_api_url }}"
        auth: "{{ zabbix_token.auth }}"
        host: "{{ vm_name }}"
        interfaces:
          - type: 1  # Interface de rede (1 = agente Zabbix)
            main: 1
            useip: 1
            ip: "{{ vm_ip }}" 
            dns: ""
            port: "{{ zabbix_port }}"  # Porta do Zabbix (10050)
        groups: "{{ zabbix_groups }}"  # Grupos fixos definidos nas Extra Variables
        templates: "{{ zabbix_templates }}"  # Templates fixos definidos nas Extra Variables
      delegate_to: localhost
