---
- name: Criação de VM no vSphere via Template e Policy
  community.vmware.vmware_guest:
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: "/etc/ansible/playbooks/venv/bin/python"
    default_disk_type: "thin"  # Tipo de provisionamento para os discos

  tasks:
    - name: Criar VM a partir de Template no vSphere
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vm_datacenter }}"
        folder: "{{ vm_folder }}"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        cluster: "{{ vm_cluster }}"
        datastore: "{{ vm_datastore }}"
        networks:
          - name: "{{ vm_network }}"
        state: poweredoff  # Criando a VM desligada
        customization:
          hostname: "{{ vm_name }}"
          domain: local
        hardware:
          memory_mb: "{{ memory_gb | int * 1024 }}"  # Convertendo GB para MB
          num_cpus: "{{ num_cpus }}"
        wait_for_ip_address: true
        tags:
          - "{{ tag_name }}" 
      delegate_to: localhost

    # Condicional: Se o usuário optar por discos extras, incluir o playbook de discos extras
    - name: Incluir playbook de discos extras
      include_tasks: add_extra_disks.yml
      when: add_disks == "Sim"

    # Continuar o fluxo normalmente, sem discos extras, caso a resposta seja "Não"
    - name: Continuar com o fluxo sem discos extras
      debug:
        msg: "A VM será criada sem discos extras."
      when: add_disks == "Não"
